version: "3"
services:
  byte-marshall:
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
     - /byte-marshall/node_modules
     - ./:/byte-marshall
    environment:
      - NODE_ENV=Development
      - PORT=8080
    ports:
      - "8080:8080"